### ISSUE TITLE
Where is the recent HUD stuff, can't find it in the content folder

### ISSUE THREAD

**Issue by AddictArts** [MWadstein/wtf-hdi-files#1]

**Comment by AddictArts** [comment]
You can close this, I found them in your fork of the engine source as linked in the youtube video

**Comment by Mayiliuzhijiao** [comment]
Where to find it？？？

**Comment by MWadstein** [comment]
All of the recent code is under a new fork that allows me to include epic content as part of the examples here https://github.com/MWadstein/UnrealEngineProjects
